// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: rank/ranking.proto

package blogv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HotRankType 热度榜统计维度
type HotRankType int32

const (
	HotRankType_HOT_RANK_UNSPECIFIED HotRankType = 0
	HotRankType_TOTAL                HotRankType = 1 // 总榜：按全部历史浏览次数排序
	HotRankType_WEEK                 HotRankType = 2 // 周榜：仅统计过去 7 天内的浏览次数
	HotRankType_DAY                  HotRankType = 3 // 日榜：仅统计过去 24 小时内的浏览次数
)

// Enum value maps for HotRankType.
var (
	HotRankType_name = map[int32]string{
		0: "HOT_RANK_UNSPECIFIED",
		1: "TOTAL",
		2: "WEEK",
		3: "DAY",
	}
	HotRankType_value = map[string]int32{
		"HOT_RANK_UNSPECIFIED": 0,
		"TOTAL":                1,
		"WEEK":                 2,
		"DAY":                  3,
	}
)

func (x HotRankType) Enum() *HotRankType {
	p := new(HotRankType)
	*p = x
	return p
}

func (x HotRankType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HotRankType) Descriptor() protoreflect.EnumDescriptor {
	return file_rank_ranking_proto_enumTypes[0].Descriptor()
}

func (HotRankType) Type() protoreflect.EnumType {
	return &file_rank_ranking_proto_enumTypes[0]
}

func (x HotRankType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HotRankType.Descriptor instead.
func (HotRankType) EnumDescriptor() ([]byte, []int) {
	return file_rank_ranking_proto_rawDescGZIP(), []int{0}
}

// HotRankItem 热度榜单项（文章 ID + 浏览次数）
type HotRankItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id"` // 文章 ID，前端用于展示标题与跳转
	Views     int64 `protobuf:"varint,2,opt,name=views,proto3" json:"views"`                          // 在该统计维度下的浏览次数
}

func (x *HotRankItem) Reset() {
	*x = HotRankItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_ranking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotRankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotRankItem) ProtoMessage() {}

func (x *HotRankItem) ProtoReflect() protoreflect.Message {
	mi := &file_rank_ranking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotRankItem.ProtoReflect.Descriptor instead.
func (*HotRankItem) Descriptor() ([]byte, []int) {
	return file_rank_ranking_proto_rawDescGZIP(), []int{0}
}

func (x *HotRankItem) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *HotRankItem) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

// GetHotRankingRequest 获取热度榜请求（首页侧栏：总榜 / 周榜 / 日榜）
type GetHotRankingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  HotRankType `protobuf:"varint,1,opt,name=type,proto3,enum=blog.v1.HotRankType" json:"type"` // TOTAL / WEEK / DAY
	Limit int32       `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`                        // 返回条数，默认 10
}

func (x *GetHotRankingRequest) Reset() {
	*x = GetHotRankingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_ranking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotRankingRequest) ProtoMessage() {}

func (x *GetHotRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rank_ranking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotRankingRequest.ProtoReflect.Descriptor instead.
func (*GetHotRankingRequest) Descriptor() ([]byte, []int) {
	return file_rank_ranking_proto_rawDescGZIP(), []int{1}
}

func (x *GetHotRankingRequest) GetType() HotRankType {
	if x != nil {
		return x.Type
	}
	return HotRankType_HOT_RANK_UNSPECIFIED
}

func (x *GetHotRankingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetHotRankingResponse 热度榜响应
type GetHotRankingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*HotRankItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items"` // 按浏览次数降序排列，最多 limit 条
}

func (x *GetHotRankingResponse) Reset() {
	*x = GetHotRankingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_ranking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotRankingResponse) ProtoMessage() {}

func (x *GetHotRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rank_ranking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotRankingResponse.ProtoReflect.Descriptor instead.
func (*GetHotRankingResponse) Descriptor() ([]byte, []int) {
	return file_rank_ranking_proto_rawDescGZIP(), []int{2}
}

func (x *GetHotRankingResponse) GetItems() []*HotRankItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_rank_ranking_proto protoreflect.FileDescriptor

var file_rank_ranking_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x61, 0x6e, 0x6b, 0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x0b, 0x48,
	0x6f, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x65,
	0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x22,
	0x56, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x6f, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x43, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x48, 0x6f,
	0x74, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x74, 0x52, 0x61, 0x6e,
	0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2a, 0x45, 0x0a, 0x0b,
	0x48, 0x6f, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x48,
	0x4f, 0x54, 0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x4f, 0x54, 0x41, 0x4c, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x57, 0x45, 0x45, 0x4b, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x41,
	0x59, 0x10, 0x03, 0x32, 0x7f, 0x0a, 0x0e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x42, 0x1b, 0x5a, 0x19, 0x79, 0x6f, 0x75, 0x72, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x6c, 0x6f, 0x67, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rank_ranking_proto_rawDescOnce sync.Once
	file_rank_ranking_proto_rawDescData = file_rank_ranking_proto_rawDesc
)

func file_rank_ranking_proto_rawDescGZIP() []byte {
	file_rank_ranking_proto_rawDescOnce.Do(func() {
		file_rank_ranking_proto_rawDescData = protoimpl.X.CompressGZIP(file_rank_ranking_proto_rawDescData)
	})
	return file_rank_ranking_proto_rawDescData
}

var file_rank_ranking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rank_ranking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rank_ranking_proto_goTypes = []interface{}{
	(HotRankType)(0),              // 0: blog.v1.HotRankType
	(*HotRankItem)(nil),           // 1: blog.v1.HotRankItem
	(*GetHotRankingRequest)(nil),  // 2: blog.v1.GetHotRankingRequest
	(*GetHotRankingResponse)(nil), // 3: blog.v1.GetHotRankingResponse
}
var file_rank_ranking_proto_depIdxs = []int32{
	0, // 0: blog.v1.GetHotRankingRequest.type:type_name -> blog.v1.HotRankType
	1, // 1: blog.v1.GetHotRankingResponse.items:type_name -> blog.v1.HotRankItem
	2, // 2: blog.v1.RankingService.GetHotRanking:input_type -> blog.v1.GetHotRankingRequest
	3, // 3: blog.v1.RankingService.GetHotRanking:output_type -> blog.v1.GetHotRankingResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rank_ranking_proto_init() }
func file_rank_ranking_proto_init() {
	if File_rank_ranking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rank_ranking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotRankItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_ranking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHotRankingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_ranking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHotRankingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rank_ranking_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rank_ranking_proto_goTypes,
		DependencyIndexes: file_rank_ranking_proto_depIdxs,
		EnumInfos:         file_rank_ranking_proto_enumTypes,
		MessageInfos:      file_rank_ranking_proto_msgTypes,
	}.Build()
	File_rank_ranking_proto = out.File
	file_rank_ranking_proto_rawDesc = nil
	file_rank_ranking_proto_goTypes = nil
	file_rank_ranking_proto_depIdxs = nil
}
