// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.21.9
// source: rank/ranking.proto

package blogv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRankingServiceGetHotRanking = "/blog.v1.RankingService/GetHotRanking"

type RankingServiceHTTPServer interface {
	// GetHotRanking 获取热度榜：总榜 / 周榜 / 日榜，按浏览次数降序
	GetHotRanking(context.Context, *GetHotRankingRequest) (*GetHotRankingResponse, error)
}

func RegisterRankingServiceHTTPServer(s *http.Server, srv RankingServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/articles/ranking", _RankingService_GetHotRanking0_HTTP_Handler(srv))
}

func _RankingService_GetHotRanking0_HTTP_Handler(srv RankingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetHotRankingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRankingServiceGetHotRanking)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHotRanking(ctx, req.(*GetHotRankingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetHotRankingResponse)
		return ctx.Result(200, reply)
	}
}

type RankingServiceHTTPClient interface {
	// GetHotRanking 获取热度榜：总榜 / 周榜 / 日榜，按浏览次数降序
	GetHotRanking(ctx context.Context, req *GetHotRankingRequest, opts ...http.CallOption) (rsp *GetHotRankingResponse, err error)
}

type RankingServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRankingServiceHTTPClient(client *http.Client) RankingServiceHTTPClient {
	return &RankingServiceHTTPClientImpl{client}
}

// GetHotRanking 获取热度榜：总榜 / 周榜 / 日榜，按浏览次数降序
func (c *RankingServiceHTTPClientImpl) GetHotRanking(ctx context.Context, in *GetHotRankingRequest, opts ...http.CallOption) (*GetHotRankingResponse, error) {
	var out GetHotRankingResponse
	pattern := "/api/articles/ranking"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRankingServiceGetHotRanking))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
