// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.21.9
// source: article/article.proto

package blogv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationArticleServiceCreateArticle = "/blog.v1.ArticleService/CreateArticle"
const OperationArticleServiceGetArticle = "/blog.v1.ArticleService/GetArticle"
const OperationArticleServiceListArticles = "/blog.v1.ArticleService/ListArticles"
const OperationArticleServiceListFeaturedArticles = "/blog.v1.ArticleService/ListFeaturedArticles"
const OperationArticleServiceListMyArticles = "/blog.v1.ArticleService/ListMyArticles"
const OperationArticleServiceRecordView = "/blog.v1.ArticleService/RecordView"
const OperationArticleServiceUpdateArticle = "/blog.v1.ArticleService/UpdateArticle"

type ArticleServiceHTTPServer interface {
	// CreateArticle 创建文章：新写一篇，可保存为草稿或直接发布
	CreateArticle(context.Context, *CreateArticleRequest) (*CreateArticleResponse, error)
	// GetArticle 文章详情：单篇元数据 + 正文 HTML，用于文章详情页（id 通过 query 传递）
	GetArticle(context.Context, *GetArticleRequest) (*GetArticleResponse, error)
	// ListArticles 文章列表：首页推荐与瀑布流，支持关键词搜索与游标分页
	ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error)
	// ListFeaturedArticles 推荐精选：从配置文件读取文章 ID 列表，查表返回
	ListFeaturedArticles(context.Context, *ListFeaturedArticlesRequest) (*ListFeaturedArticlesResponse, error)
	// ListMyArticles 我的文章列表：当前用户创建的文章（含草稿），支持分页
	ListMyArticles(context.Context, *ListMyArticlesRequest) (*ListMyArticlesResponse, error)
	// RecordView 记录文章被浏览一次，用于热度榜统计（article_id 在 body 中）
	RecordView(context.Context, *RecordViewRequest) (*RecordViewResponse, error)
	// UpdateArticle 更新文章：编辑已有文章，可修改标题/简介/封面/正文/状态（草稿或发布），id 在 body 中
	UpdateArticle(context.Context, *UpdateArticleRequest) (*UpdateArticleResponse, error)
}

func RegisterArticleServiceHTTPServer(s *http.Server, srv ArticleServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/articles", _ArticleService_ListArticles0_HTTP_Handler(srv))
	r.GET("/api/articles/featured", _ArticleService_ListFeaturedArticles0_HTTP_Handler(srv))
	r.GET("/api/articles/detail", _ArticleService_GetArticle0_HTTP_Handler(srv))
	r.GET("/api/articles/mine", _ArticleService_ListMyArticles0_HTTP_Handler(srv))
	r.POST("/api/articles", _ArticleService_CreateArticle0_HTTP_Handler(srv))
	r.POST("/api/articles/update", _ArticleService_UpdateArticle0_HTTP_Handler(srv))
	r.POST("/api/articles/view", _ArticleService_RecordView0_HTTP_Handler(srv))
}

func _ArticleService_ListArticles0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListArticlesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceListArticles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListArticles(ctx, req.(*ListArticlesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListArticlesResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_ListFeaturedArticles0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFeaturedArticlesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceListFeaturedArticles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFeaturedArticles(ctx, req.(*ListFeaturedArticlesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFeaturedArticlesResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_GetArticle0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArticleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceGetArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArticle(ctx, req.(*GetArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetArticleResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_ListMyArticles0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMyArticlesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceListMyArticles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyArticles(ctx, req.(*ListMyArticlesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMyArticlesResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_CreateArticle0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateArticleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceCreateArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateArticle(ctx, req.(*CreateArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateArticleResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_UpdateArticle0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateArticleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceUpdateArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateArticle(ctx, req.(*UpdateArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateArticleResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_RecordView0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RecordViewRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceRecordView)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RecordView(ctx, req.(*RecordViewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RecordViewResponse)
		return ctx.Result(200, reply)
	}
}

type ArticleServiceHTTPClient interface {
	// CreateArticle 创建文章：新写一篇，可保存为草稿或直接发布
	CreateArticle(ctx context.Context, req *CreateArticleRequest, opts ...http.CallOption) (rsp *CreateArticleResponse, err error)
	// GetArticle 文章详情：单篇元数据 + 正文 HTML，用于文章详情页（id 通过 query 传递）
	GetArticle(ctx context.Context, req *GetArticleRequest, opts ...http.CallOption) (rsp *GetArticleResponse, err error)
	// ListArticles 文章列表：首页推荐与瀑布流，支持关键词搜索与游标分页
	ListArticles(ctx context.Context, req *ListArticlesRequest, opts ...http.CallOption) (rsp *ListArticlesResponse, err error)
	// ListFeaturedArticles 推荐精选：从配置文件读取文章 ID 列表，查表返回
	ListFeaturedArticles(ctx context.Context, req *ListFeaturedArticlesRequest, opts ...http.CallOption) (rsp *ListFeaturedArticlesResponse, err error)
	// ListMyArticles 我的文章列表：当前用户创建的文章（含草稿），支持分页
	ListMyArticles(ctx context.Context, req *ListMyArticlesRequest, opts ...http.CallOption) (rsp *ListMyArticlesResponse, err error)
	// RecordView 记录文章被浏览一次，用于热度榜统计（article_id 在 body 中）
	RecordView(ctx context.Context, req *RecordViewRequest, opts ...http.CallOption) (rsp *RecordViewResponse, err error)
	// UpdateArticle 更新文章：编辑已有文章，可修改标题/简介/封面/正文/状态（草稿或发布），id 在 body 中
	UpdateArticle(ctx context.Context, req *UpdateArticleRequest, opts ...http.CallOption) (rsp *UpdateArticleResponse, err error)
}

type ArticleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewArticleServiceHTTPClient(client *http.Client) ArticleServiceHTTPClient {
	return &ArticleServiceHTTPClientImpl{client}
}

// CreateArticle 创建文章：新写一篇，可保存为草稿或直接发布
func (c *ArticleServiceHTTPClientImpl) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...http.CallOption) (*CreateArticleResponse, error) {
	var out CreateArticleResponse
	pattern := "/api/articles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArticleServiceCreateArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetArticle 文章详情：单篇元数据 + 正文 HTML，用于文章详情页（id 通过 query 传递）
func (c *ArticleServiceHTTPClientImpl) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...http.CallOption) (*GetArticleResponse, error) {
	var out GetArticleResponse
	pattern := "/api/articles/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleServiceGetArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListArticles 文章列表：首页推荐与瀑布流，支持关键词搜索与游标分页
func (c *ArticleServiceHTTPClientImpl) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...http.CallOption) (*ListArticlesResponse, error) {
	var out ListArticlesResponse
	pattern := "/api/articles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleServiceListArticles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListFeaturedArticles 推荐精选：从配置文件读取文章 ID 列表，查表返回
func (c *ArticleServiceHTTPClientImpl) ListFeaturedArticles(ctx context.Context, in *ListFeaturedArticlesRequest, opts ...http.CallOption) (*ListFeaturedArticlesResponse, error) {
	var out ListFeaturedArticlesResponse
	pattern := "/api/articles/featured"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleServiceListFeaturedArticles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMyArticles 我的文章列表：当前用户创建的文章（含草稿），支持分页
func (c *ArticleServiceHTTPClientImpl) ListMyArticles(ctx context.Context, in *ListMyArticlesRequest, opts ...http.CallOption) (*ListMyArticlesResponse, error) {
	var out ListMyArticlesResponse
	pattern := "/api/articles/mine"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleServiceListMyArticles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RecordView 记录文章被浏览一次，用于热度榜统计（article_id 在 body 中）
func (c *ArticleServiceHTTPClientImpl) RecordView(ctx context.Context, in *RecordViewRequest, opts ...http.CallOption) (*RecordViewResponse, error) {
	var out RecordViewResponse
	pattern := "/api/articles/view"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArticleServiceRecordView))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateArticle 更新文章：编辑已有文章，可修改标题/简介/封面/正文/状态（草稿或发布），id 在 body 中
func (c *ArticleServiceHTTPClientImpl) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...http.CallOption) (*UpdateArticleResponse, error) {
	var out UpdateArticleResponse
	pattern := "/api/articles/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArticleServiceUpdateArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
