// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: article/article.proto

package blogv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Author with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Author) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Author with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AuthorMultiError, or nil if none found.
func (m *Author) ValidateAll() error {
	return m.validate(true)
}

func (m *Author) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Avatar

	if len(errors) > 0 {
		return AuthorMultiError(errors)
	}

	return nil
}

// AuthorMultiError is an error wrapping multiple validation errors returned by
// Author.ValidateAll() if the designated constraints aren't met.
type AuthorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthorMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthorMultiError) AllErrors() []error { return m }

// AuthorValidationError is the validation error returned by Author.Validate if
// the designated constraints aren't met.
type AuthorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthorValidationError) ErrorName() string { return "AuthorValidationError" }

// Error satisfies the builtin error interface
func (e AuthorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthor.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthorValidationError{}

// Validate checks the field values on Article with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Article) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Article with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ArticleMultiError, or nil if none found.
func (m *Article) ValidateAll() error {
	return m.validate(true)
}

func (m *Article) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Summary

	if all {
		switch v := interface{}(m.GetAuthor()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ArticleValidationError{
					field:  "Author",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ArticleValidationError{
					field:  "Author",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ArticleValidationError{
				field:  "Author",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PublishedAt

	// no validation rules for Cover

	// no validation rules for Status

	// no validation rules for Visibility

	// no validation rules for LikeCount

	// no validation rules for FavoriteCount

	if len(errors) > 0 {
		return ArticleMultiError(errors)
	}

	return nil
}

// ArticleMultiError is an error wrapping multiple validation errors returned
// by Article.ValidateAll() if the designated constraints aren't met.
type ArticleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleMultiError) AllErrors() []error { return m }

// ArticleValidationError is the validation error returned by Article.Validate
// if the designated constraints aren't met.
type ArticleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleValidationError) ErrorName() string { return "ArticleValidationError" }

// Error satisfies the builtin error interface
func (e ArticleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticle.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleValidationError{}

// Validate checks the field values on ListArticlesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListArticlesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListArticlesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListArticlesRequestMultiError, or nil if none found.
func (m *ListArticlesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListArticlesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Q

	// no validation rules for Cursor

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListArticlesRequestMultiError(errors)
	}

	return nil
}

// ListArticlesRequestMultiError is an error wrapping multiple validation
// errors returned by ListArticlesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListArticlesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListArticlesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListArticlesRequestMultiError) AllErrors() []error { return m }

// ListArticlesRequestValidationError is the validation error returned by
// ListArticlesRequest.Validate if the designated constraints aren't met.
type ListArticlesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListArticlesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListArticlesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListArticlesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListArticlesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListArticlesRequestValidationError) ErrorName() string {
	return "ListArticlesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListArticlesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListArticlesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListArticlesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListArticlesRequestValidationError{}

// Validate checks the field values on ListArticlesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListArticlesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListArticlesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListArticlesResponseMultiError, or nil if none found.
func (m *ListArticlesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListArticlesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetArticles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListArticlesResponseValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListArticlesResponseValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListArticlesResponseValidationError{
					field:  fmt.Sprintf("Articles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextCursor

	if len(errors) > 0 {
		return ListArticlesResponseMultiError(errors)
	}

	return nil
}

// ListArticlesResponseMultiError is an error wrapping multiple validation
// errors returned by ListArticlesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListArticlesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListArticlesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListArticlesResponseMultiError) AllErrors() []error { return m }

// ListArticlesResponseValidationError is the validation error returned by
// ListArticlesResponse.Validate if the designated constraints aren't met.
type ListArticlesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListArticlesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListArticlesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListArticlesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListArticlesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListArticlesResponseValidationError) ErrorName() string {
	return "ListArticlesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListArticlesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListArticlesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListArticlesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListArticlesResponseValidationError{}

// Validate checks the field values on ListFeaturedArticlesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListFeaturedArticlesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListFeaturedArticlesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListFeaturedArticlesRequestMultiError, or nil if none found.
func (m *ListFeaturedArticlesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListFeaturedArticlesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListFeaturedArticlesRequestMultiError(errors)
	}

	return nil
}

// ListFeaturedArticlesRequestMultiError is an error wrapping multiple
// validation errors returned by ListFeaturedArticlesRequest.ValidateAll() if
// the designated constraints aren't met.
type ListFeaturedArticlesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListFeaturedArticlesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListFeaturedArticlesRequestMultiError) AllErrors() []error { return m }

// ListFeaturedArticlesRequestValidationError is the validation error returned
// by ListFeaturedArticlesRequest.Validate if the designated constraints
// aren't met.
type ListFeaturedArticlesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFeaturedArticlesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFeaturedArticlesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFeaturedArticlesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFeaturedArticlesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFeaturedArticlesRequestValidationError) ErrorName() string {
	return "ListFeaturedArticlesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListFeaturedArticlesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFeaturedArticlesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFeaturedArticlesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFeaturedArticlesRequestValidationError{}

// Validate checks the field values on ListFeaturedArticlesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListFeaturedArticlesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListFeaturedArticlesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListFeaturedArticlesResponseMultiError, or nil if none found.
func (m *ListFeaturedArticlesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListFeaturedArticlesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetArticles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListFeaturedArticlesResponseValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListFeaturedArticlesResponseValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListFeaturedArticlesResponseValidationError{
					field:  fmt.Sprintf("Articles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListFeaturedArticlesResponseMultiError(errors)
	}

	return nil
}

// ListFeaturedArticlesResponseMultiError is an error wrapping multiple
// validation errors returned by ListFeaturedArticlesResponse.ValidateAll() if
// the designated constraints aren't met.
type ListFeaturedArticlesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListFeaturedArticlesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListFeaturedArticlesResponseMultiError) AllErrors() []error { return m }

// ListFeaturedArticlesResponseValidationError is the validation error returned
// by ListFeaturedArticlesResponse.Validate if the designated constraints
// aren't met.
type ListFeaturedArticlesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFeaturedArticlesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFeaturedArticlesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFeaturedArticlesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFeaturedArticlesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFeaturedArticlesResponseValidationError) ErrorName() string {
	return "ListFeaturedArticlesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListFeaturedArticlesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFeaturedArticlesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFeaturedArticlesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFeaturedArticlesResponseValidationError{}

// Validate checks the field values on GetArticleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetArticleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticleRequestMultiError, or nil if none found.
func (m *GetArticleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetArticleRequestMultiError(errors)
	}

	return nil
}

// GetArticleRequestMultiError is an error wrapping multiple validation errors
// returned by GetArticleRequest.ValidateAll() if the designated constraints
// aren't met.
type GetArticleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleRequestMultiError) AllErrors() []error { return m }

// GetArticleRequestValidationError is the validation error returned by
// GetArticleRequest.Validate if the designated constraints aren't met.
type GetArticleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleRequestValidationError) ErrorName() string {
	return "GetArticleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetArticleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleRequestValidationError{}

// Validate checks the field values on ArticleEngagement with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ArticleEngagement) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArticleEngagement with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ArticleEngagementMultiError, or nil if none found.
func (m *ArticleEngagement) ValidateAll() error {
	return m.validate(true)
}

func (m *ArticleEngagement) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LikeCount

	// no validation rules for FavoriteCount

	// no validation rules for Liked

	// no validation rules for Favorited

	if len(errors) > 0 {
		return ArticleEngagementMultiError(errors)
	}

	return nil
}

// ArticleEngagementMultiError is an error wrapping multiple validation errors
// returned by ArticleEngagement.ValidateAll() if the designated constraints
// aren't met.
type ArticleEngagementMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleEngagementMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleEngagementMultiError) AllErrors() []error { return m }

// ArticleEngagementValidationError is the validation error returned by
// ArticleEngagement.Validate if the designated constraints aren't met.
type ArticleEngagementValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleEngagementValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleEngagementValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleEngagementValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleEngagementValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleEngagementValidationError) ErrorName() string {
	return "ArticleEngagementValidationError"
}

// Error satisfies the builtin error interface
func (e ArticleEngagementValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticleEngagement.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleEngagementValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleEngagementValidationError{}

// Validate checks the field values on GetArticleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetArticleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticleResponseMultiError, or nil if none found.
func (m *GetArticleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetArticle()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetArticleResponseValidationError{
					field:  "Article",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetArticleResponseValidationError{
					field:  "Article",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetArticle()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetArticleResponseValidationError{
				field:  "Article",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for BodyHtml

	if all {
		switch v := interface{}(m.GetEngagement()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetArticleResponseValidationError{
					field:  "Engagement",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetArticleResponseValidationError{
					field:  "Engagement",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEngagement()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetArticleResponseValidationError{
				field:  "Engagement",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetArticleResponseMultiError(errors)
	}

	return nil
}

// GetArticleResponseMultiError is an error wrapping multiple validation errors
// returned by GetArticleResponse.ValidateAll() if the designated constraints
// aren't met.
type GetArticleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleResponseMultiError) AllErrors() []error { return m }

// GetArticleResponseValidationError is the validation error returned by
// GetArticleResponse.Validate if the designated constraints aren't met.
type GetArticleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleResponseValidationError) ErrorName() string {
	return "GetArticleResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetArticleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleResponseValidationError{}

// Validate checks the field values on ListMyArticlesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMyArticlesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMyArticlesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMyArticlesRequestMultiError, or nil if none found.
func (m *ListMyArticlesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMyArticlesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListMyArticlesRequestMultiError(errors)
	}

	return nil
}

// ListMyArticlesRequestMultiError is an error wrapping multiple validation
// errors returned by ListMyArticlesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListMyArticlesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMyArticlesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMyArticlesRequestMultiError) AllErrors() []error { return m }

// ListMyArticlesRequestValidationError is the validation error returned by
// ListMyArticlesRequest.Validate if the designated constraints aren't met.
type ListMyArticlesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMyArticlesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMyArticlesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMyArticlesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMyArticlesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMyArticlesRequestValidationError) ErrorName() string {
	return "ListMyArticlesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListMyArticlesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMyArticlesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMyArticlesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMyArticlesRequestValidationError{}

// Validate checks the field values on ListMyArticlesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMyArticlesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMyArticlesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMyArticlesResponseMultiError, or nil if none found.
func (m *ListMyArticlesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMyArticlesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetArticles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMyArticlesResponseValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMyArticlesResponseValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMyArticlesResponseValidationError{
					field:  fmt.Sprintf("Articles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListMyArticlesResponseMultiError(errors)
	}

	return nil
}

// ListMyArticlesResponseMultiError is an error wrapping multiple validation
// errors returned by ListMyArticlesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListMyArticlesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMyArticlesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMyArticlesResponseMultiError) AllErrors() []error { return m }

// ListMyArticlesResponseValidationError is the validation error returned by
// ListMyArticlesResponse.Validate if the designated constraints aren't met.
type ListMyArticlesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMyArticlesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMyArticlesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMyArticlesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMyArticlesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMyArticlesResponseValidationError) ErrorName() string {
	return "ListMyArticlesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMyArticlesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMyArticlesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMyArticlesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMyArticlesResponseValidationError{}

// Validate checks the field values on CreateArticleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateArticleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateArticleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateArticleRequestMultiError, or nil if none found.
func (m *CreateArticleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateArticleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for Cover

	// no validation rules for BodyHtml

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateArticleRequestMultiError(errors)
	}

	return nil
}

// CreateArticleRequestMultiError is an error wrapping multiple validation
// errors returned by CreateArticleRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateArticleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateArticleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateArticleRequestMultiError) AllErrors() []error { return m }

// CreateArticleRequestValidationError is the validation error returned by
// CreateArticleRequest.Validate if the designated constraints aren't met.
type CreateArticleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateArticleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateArticleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateArticleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateArticleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateArticleRequestValidationError) ErrorName() string {
	return "CreateArticleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateArticleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateArticleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateArticleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateArticleRequestValidationError{}

// Validate checks the field values on CreateArticleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateArticleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateArticleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateArticleResponseMultiError, or nil if none found.
func (m *CreateArticleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateArticleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateArticleResponseMultiError(errors)
	}

	return nil
}

// CreateArticleResponseMultiError is an error wrapping multiple validation
// errors returned by CreateArticleResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateArticleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateArticleResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateArticleResponseMultiError) AllErrors() []error { return m }

// CreateArticleResponseValidationError is the validation error returned by
// CreateArticleResponse.Validate if the designated constraints aren't met.
type CreateArticleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateArticleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateArticleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateArticleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateArticleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateArticleResponseValidationError) ErrorName() string {
	return "CreateArticleResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateArticleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateArticleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateArticleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateArticleResponseValidationError{}

// Validate checks the field values on UpdateArticleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateArticleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateArticleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateArticleRequestMultiError, or nil if none found.
func (m *UpdateArticleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateArticleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.Title != nil {
		// no validation rules for Title
	}

	if m.Summary != nil {
		// no validation rules for Summary
	}

	if m.Cover != nil {
		// no validation rules for Cover
	}

	if m.BodyHtml != nil {
		// no validation rules for BodyHtml
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.Visibility != nil {
		// no validation rules for Visibility
	}

	if len(errors) > 0 {
		return UpdateArticleRequestMultiError(errors)
	}

	return nil
}

// UpdateArticleRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateArticleRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateArticleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateArticleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateArticleRequestMultiError) AllErrors() []error { return m }

// UpdateArticleRequestValidationError is the validation error returned by
// UpdateArticleRequest.Validate if the designated constraints aren't met.
type UpdateArticleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateArticleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateArticleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateArticleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateArticleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateArticleRequestValidationError) ErrorName() string {
	return "UpdateArticleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateArticleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateArticleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateArticleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateArticleRequestValidationError{}

// Validate checks the field values on UpdateArticleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateArticleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateArticleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateArticleResponseMultiError, or nil if none found.
func (m *UpdateArticleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateArticleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ok

	if len(errors) > 0 {
		return UpdateArticleResponseMultiError(errors)
	}

	return nil
}

// UpdateArticleResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateArticleResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateArticleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateArticleResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateArticleResponseMultiError) AllErrors() []error { return m }

// UpdateArticleResponseValidationError is the validation error returned by
// UpdateArticleResponse.Validate if the designated constraints aren't met.
type UpdateArticleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateArticleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateArticleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateArticleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateArticleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateArticleResponseValidationError) ErrorName() string {
	return "UpdateArticleResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateArticleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateArticleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateArticleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateArticleResponseValidationError{}

// Validate checks the field values on RecordViewRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RecordViewRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RecordViewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RecordViewRequestMultiError, or nil if none found.
func (m *RecordViewRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RecordViewRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ArticleId

	if len(errors) > 0 {
		return RecordViewRequestMultiError(errors)
	}

	return nil
}

// RecordViewRequestMultiError is an error wrapping multiple validation errors
// returned by RecordViewRequest.ValidateAll() if the designated constraints
// aren't met.
type RecordViewRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RecordViewRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RecordViewRequestMultiError) AllErrors() []error { return m }

// RecordViewRequestValidationError is the validation error returned by
// RecordViewRequest.Validate if the designated constraints aren't met.
type RecordViewRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RecordViewRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RecordViewRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RecordViewRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RecordViewRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RecordViewRequestValidationError) ErrorName() string {
	return "RecordViewRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RecordViewRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRecordViewRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RecordViewRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RecordViewRequestValidationError{}

// Validate checks the field values on RecordViewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RecordViewResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RecordViewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RecordViewResponseMultiError, or nil if none found.
func (m *RecordViewResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RecordViewResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RecordViewResponseMultiError(errors)
	}

	return nil
}

// RecordViewResponseMultiError is an error wrapping multiple validation errors
// returned by RecordViewResponse.ValidateAll() if the designated constraints
// aren't met.
type RecordViewResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RecordViewResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RecordViewResponseMultiError) AllErrors() []error { return m }

// RecordViewResponseValidationError is the validation error returned by
// RecordViewResponse.Validate if the designated constraints aren't met.
type RecordViewResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RecordViewResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RecordViewResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RecordViewResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RecordViewResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RecordViewResponseValidationError) ErrorName() string {
	return "RecordViewResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RecordViewResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRecordViewResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RecordViewResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RecordViewResponseValidationError{}

// Validate checks the field values on ToggleArticleLikeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ToggleArticleLikeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToggleArticleLikeRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ToggleArticleLikeRequestMultiError, or nil if none found.
func (m *ToggleArticleLikeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ToggleArticleLikeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ArticleId

	if len(errors) > 0 {
		return ToggleArticleLikeRequestMultiError(errors)
	}

	return nil
}

// ToggleArticleLikeRequestMultiError is an error wrapping multiple validation
// errors returned by ToggleArticleLikeRequest.ValidateAll() if the designated
// constraints aren't met.
type ToggleArticleLikeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToggleArticleLikeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToggleArticleLikeRequestMultiError) AllErrors() []error { return m }

// ToggleArticleLikeRequestValidationError is the validation error returned by
// ToggleArticleLikeRequest.Validate if the designated constraints aren't met.
type ToggleArticleLikeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToggleArticleLikeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToggleArticleLikeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToggleArticleLikeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToggleArticleLikeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToggleArticleLikeRequestValidationError) ErrorName() string {
	return "ToggleArticleLikeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ToggleArticleLikeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToggleArticleLikeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToggleArticleLikeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToggleArticleLikeRequestValidationError{}

// Validate checks the field values on ToggleArticleLikeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ToggleArticleLikeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToggleArticleLikeResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ToggleArticleLikeResponseMultiError, or nil if none found.
func (m *ToggleArticleLikeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ToggleArticleLikeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LikeCount

	// no validation rules for Liked

	if len(errors) > 0 {
		return ToggleArticleLikeResponseMultiError(errors)
	}

	return nil
}

// ToggleArticleLikeResponseMultiError is an error wrapping multiple validation
// errors returned by ToggleArticleLikeResponse.ValidateAll() if the
// designated constraints aren't met.
type ToggleArticleLikeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToggleArticleLikeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToggleArticleLikeResponseMultiError) AllErrors() []error { return m }

// ToggleArticleLikeResponseValidationError is the validation error returned by
// ToggleArticleLikeResponse.Validate if the designated constraints aren't met.
type ToggleArticleLikeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToggleArticleLikeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToggleArticleLikeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToggleArticleLikeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToggleArticleLikeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToggleArticleLikeResponseValidationError) ErrorName() string {
	return "ToggleArticleLikeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ToggleArticleLikeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToggleArticleLikeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToggleArticleLikeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToggleArticleLikeResponseValidationError{}

// Validate checks the field values on ToggleArticleFavoriteRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ToggleArticleFavoriteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToggleArticleFavoriteRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ToggleArticleFavoriteRequestMultiError, or nil if none found.
func (m *ToggleArticleFavoriteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ToggleArticleFavoriteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ArticleId

	if len(errors) > 0 {
		return ToggleArticleFavoriteRequestMultiError(errors)
	}

	return nil
}

// ToggleArticleFavoriteRequestMultiError is an error wrapping multiple
// validation errors returned by ToggleArticleFavoriteRequest.ValidateAll() if
// the designated constraints aren't met.
type ToggleArticleFavoriteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToggleArticleFavoriteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToggleArticleFavoriteRequestMultiError) AllErrors() []error { return m }

// ToggleArticleFavoriteRequestValidationError is the validation error returned
// by ToggleArticleFavoriteRequest.Validate if the designated constraints
// aren't met.
type ToggleArticleFavoriteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToggleArticleFavoriteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToggleArticleFavoriteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToggleArticleFavoriteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToggleArticleFavoriteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToggleArticleFavoriteRequestValidationError) ErrorName() string {
	return "ToggleArticleFavoriteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ToggleArticleFavoriteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToggleArticleFavoriteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToggleArticleFavoriteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToggleArticleFavoriteRequestValidationError{}

// Validate checks the field values on ToggleArticleFavoriteResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ToggleArticleFavoriteResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToggleArticleFavoriteResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ToggleArticleFavoriteResponseMultiError, or nil if none found.
func (m *ToggleArticleFavoriteResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ToggleArticleFavoriteResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FavoriteCount

	// no validation rules for Favorited

	if len(errors) > 0 {
		return ToggleArticleFavoriteResponseMultiError(errors)
	}

	return nil
}

// ToggleArticleFavoriteResponseMultiError is an error wrapping multiple
// validation errors returned by ToggleArticleFavoriteResponse.ValidateAll()
// if the designated constraints aren't met.
type ToggleArticleFavoriteResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToggleArticleFavoriteResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToggleArticleFavoriteResponseMultiError) AllErrors() []error { return m }

// ToggleArticleFavoriteResponseValidationError is the validation error
// returned by ToggleArticleFavoriteResponse.Validate if the designated
// constraints aren't met.
type ToggleArticleFavoriteResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToggleArticleFavoriteResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToggleArticleFavoriteResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToggleArticleFavoriteResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToggleArticleFavoriteResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToggleArticleFavoriteResponseValidationError) ErrorName() string {
	return "ToggleArticleFavoriteResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ToggleArticleFavoriteResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToggleArticleFavoriteResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToggleArticleFavoriteResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToggleArticleFavoriteResponseValidationError{}

// Validate checks the field values on ListMyFavoriteArticlesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMyFavoriteArticlesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMyFavoriteArticlesRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListMyFavoriteArticlesRequestMultiError, or nil if none found.
func (m *ListMyFavoriteArticlesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMyFavoriteArticlesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListMyFavoriteArticlesRequestMultiError(errors)
	}

	return nil
}

// ListMyFavoriteArticlesRequestMultiError is an error wrapping multiple
// validation errors returned by ListMyFavoriteArticlesRequest.ValidateAll()
// if the designated constraints aren't met.
type ListMyFavoriteArticlesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMyFavoriteArticlesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMyFavoriteArticlesRequestMultiError) AllErrors() []error { return m }

// ListMyFavoriteArticlesRequestValidationError is the validation error
// returned by ListMyFavoriteArticlesRequest.Validate if the designated
// constraints aren't met.
type ListMyFavoriteArticlesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMyFavoriteArticlesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMyFavoriteArticlesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMyFavoriteArticlesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMyFavoriteArticlesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMyFavoriteArticlesRequestValidationError) ErrorName() string {
	return "ListMyFavoriteArticlesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListMyFavoriteArticlesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMyFavoriteArticlesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMyFavoriteArticlesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMyFavoriteArticlesRequestValidationError{}

// Validate checks the field values on ListMyFavoriteArticlesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMyFavoriteArticlesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMyFavoriteArticlesResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListMyFavoriteArticlesResponseMultiError, or nil if none found.
func (m *ListMyFavoriteArticlesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMyFavoriteArticlesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetArticles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMyFavoriteArticlesResponseValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMyFavoriteArticlesResponseValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMyFavoriteArticlesResponseValidationError{
					field:  fmt.Sprintf("Articles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListMyFavoriteArticlesResponseMultiError(errors)
	}

	return nil
}

// ListMyFavoriteArticlesResponseMultiError is an error wrapping multiple
// validation errors returned by ListMyFavoriteArticlesResponse.ValidateAll()
// if the designated constraints aren't met.
type ListMyFavoriteArticlesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMyFavoriteArticlesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMyFavoriteArticlesResponseMultiError) AllErrors() []error { return m }

// ListMyFavoriteArticlesResponseValidationError is the validation error
// returned by ListMyFavoriteArticlesResponse.Validate if the designated
// constraints aren't met.
type ListMyFavoriteArticlesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMyFavoriteArticlesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMyFavoriteArticlesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMyFavoriteArticlesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMyFavoriteArticlesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMyFavoriteArticlesResponseValidationError) ErrorName() string {
	return "ListMyFavoriteArticlesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMyFavoriteArticlesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMyFavoriteArticlesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMyFavoriteArticlesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMyFavoriteArticlesResponseValidationError{}
