// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.21.9
// source: comment/comment.proto

package blogv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCommentServiceAddComment = "/blog.v1.CommentService/AddComment"
const OperationCommentServiceAddReply = "/blog.v1.CommentService/AddReply"
const OperationCommentServiceListComments = "/blog.v1.CommentService/ListComments"

type CommentServiceHTTPServer interface {
	// AddComment 发表主评论（article_id 在 body 中）
	AddComment(context.Context, *AddCommentRequest) (*AddCommentResponse, error)
	// AddReply 发表回复（对主评论或对某条回复），article_id、comment_id 在 body 中
	AddReply(context.Context, *AddReplyRequest) (*AddReplyResponse, error)
	// ListComments 某篇文章的评论列表（含嵌套回复），用于详情页评论区展示（article_id 通过 query 传递）
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
}

func RegisterCommentServiceHTTPServer(s *http.Server, srv CommentServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/articles/comments", _CommentService_ListComments0_HTTP_Handler(srv))
	r.POST("/api/articles/comments", _CommentService_AddComment0_HTTP_Handler(srv))
	r.POST("/api/articles/comments/replies", _CommentService_AddReply0_HTTP_Handler(srv))
}

func _CommentService_ListComments0_HTTP_Handler(srv CommentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentServiceListComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListComments(ctx, req.(*ListCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCommentsResponse)
		return ctx.Result(200, reply)
	}
}

func _CommentService_AddComment0_HTTP_Handler(srv CommentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddCommentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentServiceAddComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddComment(ctx, req.(*AddCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddCommentResponse)
		return ctx.Result(200, reply)
	}
}

func _CommentService_AddReply0_HTTP_Handler(srv CommentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddReplyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentServiceAddReply)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddReply(ctx, req.(*AddReplyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddReplyResponse)
		return ctx.Result(200, reply)
	}
}

type CommentServiceHTTPClient interface {
	// AddComment 发表主评论（article_id 在 body 中）
	AddComment(ctx context.Context, req *AddCommentRequest, opts ...http.CallOption) (rsp *AddCommentResponse, err error)
	// AddReply 发表回复（对主评论或对某条回复），article_id、comment_id 在 body 中
	AddReply(ctx context.Context, req *AddReplyRequest, opts ...http.CallOption) (rsp *AddReplyResponse, err error)
	// ListComments 某篇文章的评论列表（含嵌套回复），用于详情页评论区展示（article_id 通过 query 传递）
	ListComments(ctx context.Context, req *ListCommentsRequest, opts ...http.CallOption) (rsp *ListCommentsResponse, err error)
}

type CommentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCommentServiceHTTPClient(client *http.Client) CommentServiceHTTPClient {
	return &CommentServiceHTTPClientImpl{client}
}

// AddComment 发表主评论（article_id 在 body 中）
func (c *CommentServiceHTTPClientImpl) AddComment(ctx context.Context, in *AddCommentRequest, opts ...http.CallOption) (*AddCommentResponse, error) {
	var out AddCommentResponse
	pattern := "/api/articles/comments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCommentServiceAddComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AddReply 发表回复（对主评论或对某条回复），article_id、comment_id 在 body 中
func (c *CommentServiceHTTPClientImpl) AddReply(ctx context.Context, in *AddReplyRequest, opts ...http.CallOption) (*AddReplyResponse, error) {
	var out AddReplyResponse
	pattern := "/api/articles/comments/replies"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCommentServiceAddReply))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListComments 某篇文章的评论列表（含嵌套回复），用于详情页评论区展示（article_id 通过 query 传递）
func (c *CommentServiceHTTPClientImpl) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...http.CallOption) (*ListCommentsResponse, error) {
	var out ListCommentsResponse
	pattern := "/api/articles/comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentServiceListComments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
