mysql:
  blog:
    db_name: "blog"
    config:
        master:
          #dsn: "root:88888888@tcp(mysql:3306)/blog?charset=utf8mb4"
          dsn: "root:88888888@tcp(192.168.134.128:30006)/blog?charset=utf8mb4"
        is_debug: true