// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/xiaomizhou28zk/zk_web/internal/app_entrance/server/http"
	article2 "github.com/xiaomizhou28zk/zk_web/internal/application/article"
	"github.com/xiaomizhou28zk/zk_web/internal/application/auth"
	comment2 "github.com/xiaomizhou28zk/zk_web/internal/application/comment"
	"github.com/xiaomizhou28zk/zk_web/internal/application/rank"
	user2 "github.com/xiaomizhou28zk/zk_web/internal/application/user"
	"github.com/xiaomizhou28zk/zk_web/internal/clients"
	"github.com/xiaomizhou28zk/zk_web/internal/config"
	"github.com/xiaomizhou28zk/zk_web/internal/repository/article"
	storage2 "github.com/xiaomizhou28zk/zk_web/internal/repository/article/storage"
	"github.com/xiaomizhou28zk/zk_web/internal/repository/comment"
	storage3 "github.com/xiaomizhou28zk/zk_web/internal/repository/comment/storage"
	"github.com/xiaomizhou28zk/zk_web/internal/repository/user"
	"github.com/xiaomizhou28zk/zk_web/internal/repository/user/storage"
)

// Injectors from wire.go:

// WireServer init kratos application.
func WireServer() (*kratos.App, func(), error) {
	blogMysqlConfig := config.GetBlogMysqlConfig()
	blogMysqlClient, cleanup, err := clients.NewBlogMysqlClient(blogMysqlConfig)
	if err != nil {
		return nil, nil, err
	}
	userMysqlStorage := storage.NewUserMysqlStorage(blogMysqlClient)
	repository := user.NewRepository(userMysqlStorage)
	userService := user2.NewUserService(repository)
	configAuth := config.GetAuthConfig()
	manager := NewAuthManager(configAuth)
	service := auth.NewService(repository, manager)
	articleMysqlStorage := storage2.NewArticleMysqlStorage(blogMysqlClient)
	articleRepository := article.NewRepository(articleMysqlStorage)
	rankService := rank.NewService(articleRepository)
	commentMysqlStorage := storage3.NewCommentMysqlStorage(blogMysqlClient)
	replyMysqlStorage := storage3.NewReplyMysqlStorage(blogMysqlClient)
	commentRepository := comment.NewRepository(commentMysqlStorage, replyMysqlStorage)
	commentService := comment2.NewService(commentRepository, articleRepository, repository)
	articleService := article2.NewService(articleRepository, repository)
	register := http.NewRegister(userService, service, rankService, commentService, articleService, manager)
	server := http.NewServer(register, manager)
	app := newServer(server)
	return app, func() {
		cleanup()
	}, nil
}
